name: Publish Snapshot
on:
  push:
    branches:
      - main
jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Snapshot
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew clean publishLibraryPublicationToSnapshotsRepository --no-parallel
